### ISSUE TITLE
Corners round, line caps rectangular

### ISSUE THREAD

**Issue by jdittrich** [tarleb/pandoc-logo#2]
Just to check – I wondered why the line caps are rectangular, whereas the outward corners of the logo are all rounded. If there is a purpose to it, its all fine, otherwise I would suggest to use round line caps for a more coherent look.

![Pandoc Logo with round line caps](https://github.com/tarleb/pandoc-logo/assets/3416487/bef15677-c545-42f3-83ee-610d6a2a61f4)

**Comment by tarleb** [comment]
Good point! Especially the top-left cap would probably look better rounded.

Maybe some small serifs at the bottom might help, too?

**Comment by jdittrich** [comment]
> Especially the top-left cap would probably look better rounded.

Give it a try!

> Maybe some small serifs at the bottom might help, too?

Maybe… I would only do that if you have experience with type design, it will be tricky to integrate, as you need to reflect that style in the rest of the icon, which currently has a relatively clean style with a constant line width and simple caps.

**Comment by tarleb** [comment]
I changed the top-bar, wdyt?

**Comment by jdittrich** [comment]
Looks good to me, though I would go all-in and have all outer corners and caps round (including the bottom ones).

**Comment by tarleb** [comment]
I didn't like it at first, but now I agree that it looks better. I'll make the change.

**Comment by tarleb** [comment]
Thanks again!
